# Generated by Django 6.0.4 on 2026-05-17 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_entities', '0005_rename_user_group_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('path', models.FilePathField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='social_entities.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
