# Generated by Django 6.0.4 on 2026-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='path',
            field=models.CharField(max_length=512),
        ),
    ]
