# Generated by Django 6.0.4 on 2026-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('xlsx', 'xlsx'), ('pdf', 'pdf')], max_length=4),
        ),
    ]
