# Generated by Django 6.0.4 on 2026-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=4),
        ),
    ]
