# Generated by Django 6.0.4 on 2026-05-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('XLSX', 'XLSX'), ('PDF', 'PDF')], max_length=4),
        ),
    ]
