# Generated by Django 6.0.5 on 2026-05-30 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0006_alter_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='type',
            new_name='format',
        ),
    ]
