# Generated by Django 6.0.5 on 2026-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_type_report_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('by_group', 'by_group'), ('comparative', 'comparative')], default='by_group', max_length=16),
            preserve_default=False,
        ),
    ]
