# Generated by Django 6.0.5 on 2026-05-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('by_group', 'by_group'), ('comparative', 'comparative')], max_length=16),
        ),
    ]
