# Generated by Django 6.0.4 on 2026-05-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0005_rename_user_group_users'),
        ('stats', '0011_alter_bestpostinfo_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot',
                                    to='social_entities.group'),
        ),
    ]
