# Generated by Django 6.0.4 on 2026-05-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0005_rename_user_group_users'),
        ('stats', '0012_alter_snapshot_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('reposts_count', models.IntegerField()),
                ('comms_count', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_night', models.BooleanField(default=False)),
                ('is_prime_time', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=False)),
                ('has_media', models.BooleanField(default=False)),
                ('text_length', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                            to='social_entities.group')),
            ],
        ),
    ]
