# Generated by Django 6.0.4 on 2026-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0013_postmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotstats',
            name='coverage',
        ),
        migrations.AddField(
            model_name='snapshotstats',
            name='ERR',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
