# Generated by Django 6.0.4 on 2026-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0014_remove_snapshotstats_coverage_snapshotstats_err'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotstats',
            name='ERR',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
