# Generated by Django 6.0.4 on 2026-05-14 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0015_alter_snapshotstats_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetrics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
