# Generated by Django 6.0.4 on 2026-05-14 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0016_postmetrics_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmetrics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
