# Generated by Django 6.0.4 on 2026-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0017_alter_postmetrics_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmetrics',
            old_name='has_media',
            new_name='has_photo',
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='er',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='is_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='is_morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='like_view_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='media_count',
            field=models.IntegerField(default=0),
        ),
    ]
