# Generated by Django 6.0.4 on 2026-05-14 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0018_rename_has_media_postmetrics_has_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='is_evening',
        ),
    ]
