# Generated by Django 6.0.4 on 2026-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0019_remove_postmetrics_is_evening'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetrics',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
