# Generated by Django 6.0.4 on 2026-05-14 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0020_postmetrics_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='media_count',
        ),
    ]
