# Generated by Django 6.0.5 on 2026-05-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_remove_postmetrics_media_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='is_lunch',
        ),
        migrations.RemoveField(
            model_name='postmetrics',
            name='is_morning',
        ),
        migrations.RemoveField(
            model_name='postmetrics',
            name='is_night',
        ),
        migrations.RemoveField(
            model_name='postmetrics',
            name='is_prime_time',
        ),
    ]
