# Generated by Django 6.0.5 on 2026-05-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_remove_postmetrics_is_lunch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='er',
        ),
    ]
