# Generated by Django 6.0.5 on 2026-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0023_remove_postmetrics_er'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmetrics',
            name='has_text',
        ),
    ]
