# Generated by Django 6.0.5 on 2026-06-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
