# Generated by Django 6.0.4 on 2026-05-11 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0004_alter_group_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='users',
        ),
    ]
