# Generated by Django 6.0.5 on 2026-05-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0005_rename_user_group_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('model', models.CharField(
                    choices=[('Ridge Regression', 'Ridge Regression'), ('Lasso Regression', 'Lasso Regression'),
                             ('Elastic Net Regression', 'Elastic Net Regression'),
                             ('Support Vector Regression', 'Support Vector Regression'),
                             ('Gradient Boosting Regressor', 'Gradient Boosting Regressor')], max_length=128)),
                ('group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_models',
                                   to='social_entities.group')),
            ],
        ),
    ]
