# Generated by Django 6.0.5 on 2026-05-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0006_predictivemodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictivemodels',
            old_name='fields',
            new_name='params',
        ),
    ]
