# Generated by Django 6.0.5 on 2026-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0007_rename_fields_predictivemodels_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivemodels',
            name='predictable_variable',
            field=models.CharField(default='likes', max_length=16),
            preserve_default=False,
        ),
    ]
