# Generated by Django 6.0.5 on 2026-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0008_predictivemodels_predictable_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivemodels',
            name='mae',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictivemodels',
            name='r2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictivemodels',
            name='residual_str',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictivemodels',
            name='rmse',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
