# Generated by Django 6.0.5 on 2026-05-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0009_predictivemodels_mae_predictivemodels_r2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictivemodels',
            old_name='residual_str',
            new_name='residual_std',
        ),
    ]
