# Generated by Django 6.0.5 on 2026-05-19 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0010_rename_residual_str_predictivemodels_residual_std'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictivemodels',
            name='params',
            field=models.JSONField(max_length=512),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=512)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('XLSX', 'XLSX'), ('PDF', 'PDF')], max_length=4)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                            related_name='report', to='social_entities.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_reports',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
