# Generated by Django 6.0.5 on 2026-05-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0011_alter_predictivemodels_params_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
