# Generated by Django 6.0.5 on 2026-05-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0012_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('collecting', 'COLLECTING'), ('success', 'SUCCESS')], default='PENDING', max_length=32),
        ),
    ]
