# Generated by Django 6.0.5 on 2026-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0013_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'PENDING'), ('COLLECTING', 'COLLECTING'), ('SUCCESS', 'SUCCESS')],
                default='PENDING', max_length=32),
        ),
    ]
