# Generated by Django 6.0.5 on 2026-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0014_alter_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='aggregated_post_data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
