# Generated by Django 6.0.5 on 2026-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0015_group_aggregated_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='aggregated_post_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
