# Generated by Django 6.0.5 on 2026-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0016_alter_group_aggregated_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivemodels',
            name='mape',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
