# Generated by Django 6.0.5 on 2026-06-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0017_predictivemodels_mape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictivemodels',
            name='mape',
        ),
    ]
