# Generated by Django 6.0.5 on 2026-06-10 18:32

import social_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=social_auth.models.default_expires_at)),
            ],
        ),
    ]
