# Generated by Django 6.0.6 on 2026-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccountdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
